version: 2
updates:
  # Dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "build(actions-deps)"
      prefix-development: "build(actions-deps-dev)"
    reviewers:
      - "rummenigged"

  # Dependencies for Gradle
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "build(gradle-deps)"
      prefix-development: "build(gradle-deps-dev)"
      include: "scope"
    ignore:
      - dependency-name: "org.jetbrains.kotlin.*"
        update-types: [ "version-update:semver-major" ]