# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
    desc "Update version name, increments the version code and build signed release"
      lane :release do |options|
        android_set_version_name(
            gradle_file: "app/build.gradle.kts",
            version_name: options[:version]
        )
        android_set_version_code(gradle_file: "app/build.gradle.kts")

        gradle(
            task: "assemble",
            build_type: "Release",
            properties: {
              "KEYSTORE_PATH" => "app/keystore.jks",
              "KEYSTORE_PASSWORD" => ENV["KEYSTORE_PASSWORD"],
              "KEY_ALIAS" => ENV["KEY_ALIAS"],
              "KEY_PASSWORD" => ENV["KEY_PASSWORD"]
            }
          )
      end

    desc "Distribute the release build to Firebase"
    lane :firebase do
      firebase_app_distribution(
        app: ENV["FIREBASE_APP_ID"],
        testers: ENV["FIREBASE_TESTERS"],
        firebase_cli_token: ENV["FIREBASE_CLI_TOKEN"],
        release_notes: "Release via semantic-release",
        android_artifact_path: "app/build/outputs/apk/release/app-release.apk"
      )
    end
end
